#use_frameworks! :linkage => :static
install! "cocoapods",
         :generate_multiple_pod_projects => true

platform :ios, '10.0'

target 'SDWebImageJPEGXLCoder_Example' do
  pod 'SDWebImageJPEGXLCoder', :path => '../'
  pod 'libjxl'
end
